import { Registry } from 'prom-client';
import type { Session, SessionEvent } from '@deepseek-ai/dsh-session';
import type { GenerateOptions, StreamChunk } from '@deepseek-ai/dsh-llm';
import type { ToolDispatchExecution, ToolExecutionResult } from '@deepseek-ai/dsh-tools';
import type { SubagentRunEndInfo, SubagentRunInfo } from '@deepseek-ai/dsh-subagent';
import type { JobSnapshot } from '@deepseek-ai/dsh-jobs';
type FaultReporter = (operation: string) => void;
/** Owns one isolated Prometheus registry and every bounded DSH instrument. */
export declare class HarnessMetrics {
    private readonly reportFault;
    readonly registry: Registry<"text/plain; version=0.0.4; charset=utf-8">;
    private readonly guard;
    private readonly turnStarts;
    private readonly stepStarts;
    private readonly subagentStarts;
    private readonly jobs;
    private readonly sessionsActive;
    private readonly turnsTotal;
    private readonly stepsTotal;
    private readonly agentErrorsTotal;
    private readonly turnDuration;
    private readonly stepDuration;
    private readonly llmRequestsTotal;
    private readonly llmDuration;
    private readonly llmInputTokens;
    private readonly llmOutputTokens;
    private readonly llmReasoningTokens;
    private readonly llmCacheReadTokens;
    private readonly llmCacheWriteTokens;
    private readonly toolCallsTotal;
    private readonly toolDuration;
    private readonly approvalRequests;
    private readonly approvalAllowed;
    private readonly approvalDenied;
    private readonly approvalCancelled;
    private readonly approvalUnavailable;
    private readonly subagentsStarted;
    private readonly subagentsCompleted;
    private readonly subagentsFailed;
    private readonly subagentDuration;
    private readonly jobsActive;
    private readonly jobsStarted;
    private readonly jobsCompleted;
    private readonly jobsKilled;
    private readonly jobsFailed;
    private readonly jobDuration;
    private readonly labelOverflow;
    constructor(options: {
        maxLabelValues: number;
        maxLabelValueLength: number;
    }, reportFault: FaultReporter);
    seedSessions(count: number): void;
    sessionCreated(): void;
    sessionDisposed(session: Session): void;
    sessionEvent(session: Session, event: SessionEvent): void;
    agentError(): void;
    llmStream(options: GenerateOptions, next: () => AsyncIterable<StreamChunk>): AsyncIterable<StreamChunk>;
    toolExecution(exec: ToolDispatchExecution, next: () => Promise<ToolExecutionResult>): Promise<ToolExecutionResult>;
    subagentStarted(info: SubagentRunInfo): void;
    subagentEnded(info: SubagentRunEndInfo): void;
    seedJobs(snapshots: readonly JobSnapshot[]): void;
    reconcileJobs(snapshots: readonly JobSnapshot[], ownerSession: string | undefined): void;
    jobDone(snapshot: JobSnapshot): void;
    dispose(): void;
    private observeUsage;
    private instrumentLlmStream;
    private adoptJob;
    private removeJob;
    private dynamic;
    private safe;
    private counter;
    private gauge;
    private histogram;
    private simpleCounter;
    private tokenCounter;
    private jobCounter;
    private mapFor;
}
export {};
//# sourceMappingURL=metrics.d.ts.map